#### This jupyter notebook is submitted as part of ML Zoomcamp. It has been shared on github to help the peers.  Contributions are welcomed.


In [1]:
import numpy as np
import pandas as pd

#### Question 1
What's the version of NumPy that you installed?

In [2]:

np.__version__

'1.20.3'

#### Question 2
What's the version of NumPy that you installed?

In [3]:
pd.__version__


'1.3.2'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [5]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
df.Make.value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

#### Question 3: 
The average price of BMW *


In [7]:
# Question 3: The average price of BMW *

filt = df.Make == 'BMW'
df[filt].MSRP.mean()

61546.76347305389

In [8]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

### Question 4
#### Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [9]:
df['Engine HP'].isna().sum()

69

In [10]:
filt2 = df['Year']>2014
df[filt2].Year.value_counts()

2015    2170
2016    2157
2017    1668
Name: Year, dtype: int64

In [11]:
df[filt2]['Engine HP'].isna().sum()   

51

### Question 5
Calculate the average "Engine HP" in the dataset.
Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
Now, calcualte the average of "Engine HP" again.
Has it changed?
Round both means before answering this questions.

In [12]:
df['Engine HP'].mean()         # mean before filling missing values

249.38607007176023

In [13]:
# no. of missing values 

df['Engine HP'].isna().sum()

69

In [14]:
x = df['Engine HP'].mean()
x

249.38607007176023

In [15]:
df['Engine HP'].fillna(round(x),inplace=True)

In [16]:
df['Engine HP'].isna().sum()          # missing values filled

0

In [17]:
df['Engine HP'].mean()              

249.3838341447037

In [18]:
round(df['Engine HP'].mean())         # Mean remains the same even after filling

249

### Question 6
Select all the "Rolls-Royce" cars from the dataset.
Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
What's the sum of all the elements of the result?
Hint: if the result is negative, re-read the task one more time

In [19]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [20]:
filt3 = df['Make'] == 'Rolls-Royce'
df[filt3][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [21]:
X = np.array(df[filt3][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates())
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [22]:
# transpose of X 

X.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [23]:
# Compute matrix-matrix multiplication between the transpose of X and X

XTX = (X.T).dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [24]:
# Invert XTX

i_XTX = np.linalg.inv(XTX)
i_XTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [25]:
# What's the sum of all the elements of the result? 

i_XTX.sum()


0.03221232067748617

### Questions 7
Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the first element of w?.

In [26]:
# Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
a = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
a

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [27]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

w = i_XTX.dot(X.T).dot(a)
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [28]:
w[0]

0.19989598183185642